spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    include: db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDB103Dialect
        default_batch_fetch_size: 1000
    open-in-view: off
    database-platform: mariadb
  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: 9000